# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Imaginary Avengers API Reference
  description: Send our Avenger on a mission!
  version: "1.0.0"
# the domain of the service
host: api.avengers.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /heroes:
    get:
      summary: List of all available heroes.
      description: Retrieves the list of available heros.
      parameters:
        - name: favourites
          in: query
          description: A filter on the list based on the hero object name field, semicolon separated for multiple names.
          required: false
          type: string
      tags:
        - Avengers
      responses:
        200:
          description: Returns a list of available hero objects in JSON format if valid objects were found.
          schema:
            type: array
            items:
              $ref: '#/definitions/Hero'
  /heroes/{hero_id}:
    get:
      summary: Retrieve a hero.
      description: Retrieves the details of an existing hero.
      parameters:
        - name: hero_id
          in: path
          description: A unique identifier of the hero.
          required: true
          type: integer
      tags:
        - Avengers
      responses:
        200:
          description: Returns a hero object in JSON format if valid identifier was provided.
          schema:
            type: object
            items:
              $ref: '#/definitions/Hero'

definitions:
  Hero:
    description: One Avenger who is available (currently not on a mission) to work for you.
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier of the hero.
      name:
        type: string
        description: Publicly vicible name of the hero.
      first_name:
        type: string
        description: Hidden actual first name of the hero.
      last_name:
        type: string
        description: Hidden actual last name of the hero.
      missions_completed:
        type: integer
        description: Count of the completed missions by the hero.
  Mission:
    description: One Avenger who is available (currently not on a mission) to work for you.
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier of the hero.
      name:
        type: string
        description: Publicly vicible name of the hero.
      first_name:
        type: string
        description: Hidden actual first name of the hero.
      last_name:
        type: string
        description: Hidden actual last name of the hero.
      missions_completed:
        type: integer
        description: Count of the completed missions by the hero.
